version: '2'
catalog:
  name: "DockerRegistry"
  version: "v0.0.2"
  description: "DockerRegistry"
  uuid: DockerRegistry-0
  minimum_rancher_version: v0.9.0
  questions:
    - variable: lb_port
      description: "Port to access PostgreSQL from external services"
      label: "Postgres LB Port"
      required: true
      default: 5000
      type: "int"
   

services:
  DockerRegistry-lb:
    scale: 1
    lb_config:
      certs: []
      port_rules:
      - protocol: tcp
        service: DockerRegistry
        source_port: ${lb_port}
        target_port: 5000
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
  DockerRegistry:
    scale: 1
    health_check:
      port: 5000
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000

